# Generated by Django 5.2.4 on 2025-07-20 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='ID único para a sessão de jogo (UUID ou similar)', max_length=100, unique=True)),
                ('theme', models.CharField(help_text='Tema do jogo (ex: Filmes, História)', max_length=50)),
                ('level', models.CharField(help_text='Nível de dificuldade (ex: Fácil, Médio, Difícil, Aleatório)', max_length=50)),
                ('character_name', models.CharField(blank=True, help_text='Nome do personagem que a IA escolheu', max_length=255, null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Indica se a sessão de jogo foi concluída')),
                ('score', models.IntegerField(default=0, help_text='Pontuação final do jogador nesta sessão')),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='Data e hora de início da sessão')),
                ('end_time', models.DateTimeField(blank=True, help_text='Data e hora de término da sessão', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'Usuário'), ('ai', 'IA')], help_text='Remetente da mensagem (usuário ou IA)', max_length=10)),
                ('message_text', models.TextField(help_text='Conteúdo da mensagem')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Data e hora da mensagem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='core.gamesession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
