# Generated by Django 5.2.4 on 2025-07-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_gamesession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='attempts_left',
            field=models.IntegerField(default=0, help_text='Número de tentativas restantes para adivinhar o personagem'),
        ),
    ]
